apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "technitium-dns-exporter.fullname" . }}-config
  labels:
    {{- include "technitium-dns-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
